name: 'Jest Coverage Commenter'
description: 'Comment on PRs with Jest Coverage Information'
author: 'Derek Kershner'
inputs:
  github_token:
    description: 'A GitHub Token, the standard one is great'
    default: 'default value if applicable'
  test_command:
    description: 'The test command to run, that also runs coverage appropriately'
    default: 'npx jest --coverage --noChangesSince=master'
runs:
  using: 'node12'
  main: 'dist/index.js'
